Add bookings
alekseybch/java-shareit pull request #2
Opened 2022-12-17 14:48 UTC by alekseybch

2022-12-18 17:23 UTC, NikolaiDem requested changes

2022-12-18 17:23 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/db/model/Booking.java
> +        return getClass().hashCode();
С какой целью переопределяются equals(...) и hashCode(...) ?

2022-12-18 17:23 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/impl/BookingServiceImpl.java
> +        }
Еще лучше проверить, что вещь не забронирована никем другим на запрашиваемые даты

2022-12-18 17:23 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/impl/BookingServiceImpl.java
> +        if (isApproved.toString().equals(booking.getStatus().getLabel())) {
Если статус уже финальный (Approved или Rejected) лучше убрать возможность редактировать такое состояние.

2022-12-18 17:23 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/db/repository/ItemRepository.java
> +            "and (lower(i.name) like %:text% " +
А без кавычек %:text% точно работает?

2022-12-18 17:23 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/dto/BookingBookerDto.java
> +}
Здесь еще должны быть даты начала и завершения бронирования, чтобы владелец мог просмотреть их.

2022-12-18 17:23 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +        if ((bookingRepository.findByItemIdAndBookerId(commentDto.getItemId(),
И бронирование должно быть подтверждено, чтобы пользователь мог оставить комментарий.

2022-12-18 17:23 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/db/repository/BookingRepository.java
> +            "and (b.end = (select max(bk.end) from Booking bk where bk.item.id in (:itemIds) and bk.end < :time) " +
Последнее бронирование может еще не закончиться (то есть важен только факт начала в прошлом).

2022-12-19 09:21 UTC, alekseybch commented
Доработана бизнес-логика:
1. Проверка запрашиваемыех дат на свободный интервал
2. Запрет на редактирование статуса, если уже Approved или Rejected
3. Добавлены поля начала и окончания бронирования в dto
4. Добавлена проверка статуса бронирования при добавлении комментария
5. Изменена логика поиска последнего бронирования вещи. Может быть незавершенным бронированием.
Fix:
1.Убраны переопределения equals(...) и hashCode(...) в Booking
2.Поправлен запрос(getByText) поиска вещи в ItemRepository

2022-12-19 21:22 UTC, NikolaiDem requested changes

2022-12-19 21:22 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/db/model/Comment.java
> +    public boolean equals(Object o) {
equals(...) и hashCode(...) аналогично не нужны и для остальных классов.

2022-12-19 21:22 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/db/repository/BookingRepository.java
> +    @Query("select b from Booking b " +
Пусть запрашиваемый отрезок бронирования [5, 10]. А уже подтвержденное бронирование таково [3, 6]. Будет ли выявлено пересечение? 
Вместо вложенных запросов достаточно условие, что дата начала бронирования находится перед завершением запрошенного бронирования, и дата завершения бронирования находится после начала запрошенного бронирования, и бронирование должно быть подтверждено.

2022-12-20 06:30 UTC, alekseybch commented
Fix:
1.Убраны переопределения equals(...) и hashCode(...) в Item, User, Comment
2.Поправлен запрос поиска свободных интервалов

2022-12-20 08:21 UTC, alekseybch commented
Fix:
1.Убраны переопределения equals(...) и hashCode(...) в Item, User, Comment
2.Поправлен запрос поиска свободных интервалов

2022-12-20 16:13 UTC, NikolaiDem approved these changes

2022-12-20 16:13 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/db/repository/BookingRepository.java
> +            "and :timeStart >= b.end " +
Только наоборот and :timeStart <= b.end and and :timeEnd >= b.start

2022-12-23 07:57 UTC, merged