add-item-requests
alekseybch/java-shareit pull request #3
Opened 2023-01-06 21:31 UTC by alekseybch

2023-01-07 22:18 UTC, NikolaiDem requested changes

2023-01-07 22:18 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/service/impl/ItemRequestServiceImpl.java
> +    @Transactional(readOnly = true)
@Transactional(readOnly = true) можно указать на уровне класса. 
А иную "транзакционность" (например, другой уровень изоляции указать для конкретных методов).
Аналогично для остальных сервисов.

2023-01-07 22:18 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/service/impl/ItemRequestServiceImpl.java
> +        getItems(itemReqDtoList);
Метод getItems(...) все же не возвращает item-ы, а добавляет их к запросам. Более подходящим названием метода было бы addItems(...)/setItems(...)

2023-01-07 22:18 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/service/impl/ItemRequestServiceImpl.java
> +        List<Item> items = itemRepository.findItemsByRequestId(itemReqIds);
Лучшее List далее преобразовать в Map, где ключ - id запроса, а значение - список вещей по этому запросу. Тогда в 102 строке не понадобится делать итерирование по всему списку items.

2023-01-07 22:18 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/global/utility/PageableConverter.java
> +        if (from < 0 || size < 0) {
Лучше у size исключить и равенство нулю, иначе может получиться деление на 0.

2023-01-07 22:18 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +        getBookingsList(itemsDto, itemIds);
Для методов с типом возвращаемого значения void лучше использовать названия set/add/update

2023-01-07 22:18 UTC, NikolaiDem commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +@SpringBootTest
Использование SpringBootTest и AutoConfigureTestDatabase создает лишний "тяжелый" слой дополнительных бинов, из-за чего тест становится почти интеграционным. Нам лишь надо протестировать контроллеры. 
Лучше использовать WebMvcTest, чтобы не создавать избыточные сервисы, репозитории и т.д. А для сервисов данного контроллера создать их моки.
Аналогично для остальных тестов контроллеров.

И еще сделать отдельные классы с полностью интеграционными тестами для некоторых пользовательских кейсов (например, создание бронирования).

2023-01-08 16:58 UTC, alekseybch commented
Исправлено согласно замечаниям:
1. @Transactional(readOnly = true) вынесен на уровень классов
2. Поправлены названия void методов
3. В ItemRequestServiceImpl setItems() переделана логика через Map
4. Добавлена проверка size на 0 при создании PageRequest
5. Переделаны все тесты тестирования контроллеров
6. Добавлены интеграционные тесты

2023-01-09 05:07 UTC, NikolaiDem approved these changes

2023-01-09 05:07 UTC, NikolaiDem commented on src/test/java/ru/practicum/shareit/booking/service/impl/BookingServiceImplTest.java
> +        bookingRequestDto.setEnd(booking1.getEnd().minusDays(1));
Изначально в booking1 end опережает start на 1 день.
После такой установки end ( bookingRequestDto.setEnd(booking1.getEnd().minusDays(1)) ) в bookingRequestDto end совпадает со start, 
Поэтому такое условие if (bookingDto.getEnd().isBefore(bookingDto.getStart())) { } будет false, так как в isBefore равенство строгое (<). И BadBookingDateException брошено не будет.
Лучше сделать end строго меньше чем start для bookingRequestDto.

2023-01-09 09:35 UTC, merged